# Uncomment the next line to define a global platform for your project
require_relative '../node_modules/react-native/scripts/react_native_pods'
# platform :ios, '9.0'

target 'TrtcCalling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrtcCalling

  pod 'TXLiteAVSDK_TRTC'
  pod 'TXIMSDK_iOS'
  pod 'MJExtension'
end
